apiVersion: v2
name: connaisseur
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "2.2.0"

dependencies:
  - name: connaisseur
    repository: https://sse-secure-systems.github.io/connaisseur/charts
    version: 2.2.0
